Repository github/vscode-codeql, pull requests merged in 2022-09, with the labels that each got.

#1490 Check CLI version and fix race condition in join-order scanning
  extensions/ql-vscode/src/cli.ts
  extensions/ql-vscode/src/run-queries.ts
Labels: bug, Complexity: Low

#1482 Bundle Codicons using Webpack
  extensions/ql-vscode/gulpfile.ts/webpack.config.ts
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/abstract-interface-manager.ts
  extensions/ql-vscode/src/interface-utils.ts
  extensions/ql-vscode/src/view/webview.tsx
Labels: secexp

#1493 v1.16.12
  extensions/ql-vscode/CHANGELOG.md
Labels: Complexity: Low

#1492 Add retry for finding result-index artifact
  extensions/ql-vscode/src/remote-queries/gh-actions-api-client.ts
  extensions/ql-vscode/src/remote-queries/remote-queries-monitor.ts
Labels: secexp

#1497 Setup Storybook for testing UI components
  .gitattributes
  .vscode/launch.json
  CONTRIBUTING.md
  extensions/ql-vscode/.npmrc
  extensions/ql-vscode/.storybook/main.ts
  extensions/ql-vscode/.storybook/manager.ts
  extensions/ql-vscode/.storybook/preview.ts
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/stories/.eslintrc.js
  extensions/ql-vscode/src/stories/Overview.stories.mdx
  extensions/ql-vscode/src/stories/images/update-css-variables-body.png
  extensions/ql-vscode/src/stories/images/update-css-variables-iframe.png
  extensions/ql-vscode/src/stories/images/update-css-variables-styles.png
  extensions/ql-vscode/src/stories/remote-queries/AnalysisAlertResult.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/CodePaths.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/DownloadButton.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/DownloadSpinner.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/FileCodeSnippet.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/LastUpdated.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/RemoteQueries.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/RepositoriesSearch.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/StarCount.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/TextButton.stories.tsx
  extensions/ql-vscode/src/stories/remote-queries/data/analysesResultsMessage.json
  extensions/ql-vscode/src/stories/remote-queries/data/remoteQueryResultMessage.json
  extensions/ql-vscode/src/stories/tsconfig.json
  extensions/ql-vscode/src/stories/vscode-theme.css
Labels: secexp

#1504 Remove query name from query ID for MRVA queries
  extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
Labels: secexp

#1503 Remove open on GitHub item from cancelled local results
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/query-history.ts
Labels: secexp

#1509 Fix ESLint VSCode configuration
  .vscode/settings.json
Labels: secexp

#1510 Renamed 'interface managers' to something more specific
  extensions/ql-vscode/src/abstract-webview.ts
  extensions/ql-vscode/src/compare/compare-view.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/interface.ts
  extensions/ql-vscode/src/query-history.ts
  extensions/ql-vscode/src/remote-queries/remote-queries-manager.ts
  extensions/ql-vscode/src/remote-queries/remote-queries-view.ts
  extensions/ql-vscode/src/remote-queries/variant-analysis-view.ts
  extensions/ql-vscode/src/vscode-tests/no-workspace/query-history.test.ts
  extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/remote-query-history.test.ts
Labels: secexp

#1518 Add correct CODEOWNERS for MRVA webviews
  CODEOWNERS
Labels: secexp

#1512 Add variant analysis top header
  .vscode/launch.json
  .vscode/settings.json
  extensions/ql-vscode/.eslintrc.js
  extensions/ql-vscode/jest.config.js
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts
  extensions/ql-vscode/src/stories/variant-analysis/QueryDetails.stories.tsx
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysis.stories.tsx
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisActions.stories.tsx
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisHeader.stories.tsx
  extensions/ql-vscode/src/view/remote-queries/ViewTitle.tsx
  extensions/ql-vscode/src/view/tsconfig.json
  extensions/ql-vscode/src/view/tsconfig.spec.json
  extensions/ql-vscode/src/view/variant-analysis/LinkIconButton.tsx
  extensions/ql-vscode/src/view/variant-analysis/QueryDetails.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisActions.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisContainer.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/QueryDetails.spec.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisActions.spec.tsx
  extensions/ql-vscode/test/__mocks__/fileMock.ts
  extensions/ql-vscode/test/__mocks__/styleMock.ts
  extensions/ql-vscode/test/jest.setup.ts
  extensions/ql-vscode/tsconfig.json
Labels: secexp

#1520 Move common React components to separate directory
  extensions/ql-vscode/src/view/common/HorizontalSpace.tsx
  extensions/ql-vscode/src/view/common/SectionTitle.tsx
  extensions/ql-vscode/src/view/common/VerticalSpace.tsx
  extensions/ql-vscode/src/view/common/ViewTitle.tsx
  extensions/ql-vscode/src/view/common/index.ts
  extensions/ql-vscode/src/view/remote-queries/CodePaths.tsx
  extensions/ql-vscode/src/view/remote-queries/FileCodeSnippet.tsx
  extensions/ql-vscode/src/view/remote-queries/RemoteQueries.tsx
  extensions/ql-vscode/src/view/variant-analysis/QueryDetails.tsx
Labels: secexp

#1521 Define variant analysis domain models
  extensions/ql-vscode/src/remote-queries/shared/repository.ts
  extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts
Labels: secexp

#1528 Fix "Export All" not always exporting the correct query
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/query-history.ts
  extensions/ql-vscode/src/remote-queries/export-results.ts
  extensions/ql-vscode/src/remote-queries/remote-queries-view.ts
  extensions/ql-vscode/src/view/remote-queries/RemoteQueries.tsx
Labels: secexp

#1517 Add variant analysis stats component
  .vscode/launch.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/pure/date.ts
  extensions/ql-vscode/src/pure/number.ts
  extensions/ql-vscode/src/pure/time.ts
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisHeader.stories.tsx
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisStats.stories.tsx
  extensions/ql-vscode/src/view/common/icon/Codicon.tsx
  extensions/ql-vscode/src/view/common/icon/ErrorIcon.tsx
  extensions/ql-vscode/src/view/common/icon/SuccessIcon.tsx
  extensions/ql-vscode/src/view/common/icon/WarningIcon.tsx
  extensions/ql-vscode/src/view/common/icon/index.ts
  extensions/ql-vscode/src/view/common/index.ts
  extensions/ql-vscode/src/view/variant-analysis/StatItem.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisRepositoriesStats.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStats.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStatusStats.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisStats.spec.tsx
  extensions/ql-vscode/test/mocha.setup.js
  extensions/ql-vscode/test/pure-tests/date.test.ts
  extensions/ql-vscode/test/pure-tests/number.test.ts
  extensions/ql-vscode/test/pure-tests/time.test.ts
Labels: secexp

#1531 Move CodePaths and FileCodeSnippet to common directory
  extensions/ql-vscode/src/stories/common/CodePaths.stories.tsx
  extensions/ql-vscode/src/stories/common/FileCodeSnippet.stories.tsx
  extensions/ql-vscode/src/view/common/CodePaths/CodePaths.tsx
  extensions/ql-vscode/src/view/common/CodePaths/index.ts
  extensions/ql-vscode/src/view/common/FileCodeSnippet/FileCodeSnippet.tsx
  extensions/ql-vscode/src/view/common/FileCodeSnippet/index.ts
  extensions/ql-vscode/src/view/common/index.ts
  extensions/ql-vscode/src/view/remote-queries/AnalysisAlertResult.tsx
Labels: secexp

#1527 Add new GitHub API client with functions for new MRVA flow
  extensions/ql-vscode/src/remote-queries/gh-api/gh-api-client.ts
  extensions/ql-vscode/src/remote-queries/gh-api/repository.ts
  extensions/ql-vscode/src/remote-queries/gh-api/variant-analysis.ts
  extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts
Labels: secexp

#1523 Refactor CodePaths and FileCodeSnippet components
  extensions/ql-vscode/src/view/common/CodePaths/CodePaths.tsx
  extensions/ql-vscode/src/view/common/FileCodeSnippet/FileCodeSnippet.tsx
Labels: secexp

#1532 Split CodePaths and FileCodeSnippet into multiple files
  extensions/ql-vscode/src/view/common/CodePaths/CodeFlowsDropdown.tsx
  extensions/ql-vscode/src/view/common/CodePaths/CodePath.tsx
  extensions/ql-vscode/src/view/common/CodePaths/CodePaths.tsx
  extensions/ql-vscode/src/view/common/CodePaths/CodePathsOverlay.tsx
  extensions/ql-vscode/src/view/common/CodePaths/ThreadPath.tsx
  extensions/ql-vscode/src/view/common/FileCodeSnippet/CodeSnippetCode.tsx
  extensions/ql-vscode/src/view/common/FileCodeSnippet/CodeSnippetLine.tsx
  extensions/ql-vscode/src/view/common/FileCodeSnippet/CodeSnippetMessage.tsx
  extensions/ql-vscode/src/view/common/FileCodeSnippet/FileCodeSnippet.tsx
Labels: secexp

#1534 Use domain model for VariantAnalysisHeader
  extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisHeader.stories.tsx
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisStats.stories.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisRepositoriesStats.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStats.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisStats.spec.tsx
Labels: secexp

#1536 Add ESLint plugin for React hooks
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/stories/.eslintrc.js
  extensions/ql-vscode/src/view/.eslintrc.js
Labels: secexp

#1537 Add Storybook stories for icons
  extensions/ql-vscode/src/stories/common/icon/Codicon.stories.tsx
  extensions/ql-vscode/src/stories/common/icon/ErrorIcon.stories.tsx
  extensions/ql-vscode/src/stories/common/icon/SuccessIcon.stories.tsx
  extensions/ql-vscode/src/stories/common/icon/WarningIcon.stories.tsx
  extensions/ql-vscode/src/stories/common/icon/vscode-icons.json
Labels: secexp

#1540 Ensure `safeMax` is safe for undefined values
  extensions/ql-vscode/src/log-insights/join-order.ts
Labels: bug, Complexity: Low

#1539 Add Alert component for showing warnings and errors
  extensions/ql-vscode/src/stories/common/Alert.stories.tsx
  extensions/ql-vscode/src/view/common/Alert.tsx
  extensions/ql-vscode/src/view/common/__tests__/Alert.spec.tsx
  extensions/ql-vscode/src/view/common/index.ts
Labels: secexp

#1541 Add loading component
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisLoading.stories.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisLoading.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisLoading.spec.tsx
Labels: secexp

#1538 Implement submitting a live-results variant analysis
  extensions/ql-vscode/src/remote-queries/gh-api/gh-api-client.ts
  extensions/ql-vscode/src/remote-queries/remote-query-submission-result.ts
  extensions/ql-vscode/src/remote-queries/run-remote-query.ts
  extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts
  extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts
  extensions/ql-vscode/src/vscode-tests/no-workspace/remote-queries/run-remote-query.test.ts
  extensions/ql-vscode/test/pure-tests/variant-analysis.test.ts
Labels: secexp

#1543 Add outcome panels
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisOutcomePanels.stories.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisAnalyzedRepos.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisNoCodeqlDbRepos.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisNotFoundRepos.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisOutcomePanels.spec.tsx
Labels: secexp

#1547 Fix not being able to run variant analyses
  extensions/ql-vscode/src/remote-queries/run-remote-query.ts
Labels: secexp

#1548 Hide repositories with raw results without rows
  extensions/ql-vscode/src/view/remote-queries/RemoteQueries.tsx
Labels: secexp

#1544 Add analyzed repositories component
  extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts
  extensions/ql-vscode/src/stories/remote-queries/data/rawResults.json
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepoItem.stories.tsx
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisAnalyzedRepos.stories.tsx
  extensions/ql-vscode/src/view/common/icon/LoadingIcon.tsx
  extensions/ql-vscode/src/view/common/icon/index.ts
  extensions/ql-vscode/src/view/variant-analysis/AnalyzedRepoItemContent.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisAnalyzedRepoItem.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisAnalyzedRepos.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/AnalyzedRepoItemContent.spec.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepoItem.spec.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisAnalyzedRepos.spec.tsx
Labels: secexp

#1545 Implement monitoring for variant analysis live results
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/remote-queries/gh-api/variant-analysis.ts
  extensions/ql-vscode/src/remote-queries/run-remote-query.ts
  extensions/ql-vscode/src/remote-queries/shared/variant-analysis-monitor-result.ts
  extensions/ql-vscode/src/remote-queries/variant-analysis-monitor.ts
  extensions/ql-vscode/src/remote-queries/variant-analysis-processor.ts
  extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/run-remote-query.test.ts
  extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-monitor.test.ts
  extensions/ql-vscode/src/vscode-tests/cli-integration/remote-queries/variant-analysis-processor.test.ts
  extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/scanned-repositories.ts
  extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/skipped-repositories.ts
  extensions/ql-vscode/src/vscode-tests/factories/remote-queries/gh-api/variant-analysis-api-response.ts
  extensions/ql-vscode/src/vscode-tests/factories/remote-queries/shared/variant-analysis-submission.ts
Labels: secexp

#1549 Implement skipped repositories tabs
  extensions/ql-vscode/src/remote-queries/shared/variant-analysis.ts
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisSkippedRepositoriesTab.stories.tsx
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisSkippedRepositoryRow.stories.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysis.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisNoCodeqlDbRepos.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisNotFoundRepos.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisOutcomePanels.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisSkippedRepositoriesTab.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisSkippedRepositoryRow.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisSkippedRepositoriesTab.spec.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisSkippedRepositoryRow.spec.tsx
Labels: secexp
