Repository github/vscode-codeql, pull requests merged in 2022-08, with the labels that each got.

#1430 Initial implementation of sourcemap-based jump-to-QL command
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/cli.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/log-insights/summary-language-support.ts
  extensions/ql-vscode/src/pure/log-summary-parser.ts
  extensions/ql-vscode/src/pure/messages.ts
  extensions/ql-vscode/src/run-queries.ts
  extensions/ql-vscode/src/vscode-tests/cli-integration/query.test.ts
  extensions/ql-vscode/src/vscode-tests/cli-integration/sourcemap.test.ts
  extensions/ql-vscode/src/vscode-tests/no-workspace/run-queries.test.ts
  extensions/ql-vscode/test/data/lib/semmle/code/cpp/Namespace.qll
  extensions/ql-vscode/test/data/log-summary/evaluator-log.summary
  extensions/ql-vscode/test/data/log-summary/evaluator-log.summary.map
Labels: Complexity: Medium

#1451 Ensure query history state is persisted after new query is added
  extensions/ql-vscode/src/query-history.ts
Labels: secexp

#1454 Report suspicious join orders
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/cli.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/log-insights/join-order.ts
  extensions/ql-vscode/src/log-insights/jsonl-reader.ts
  extensions/ql-vscode/src/log-insights/log-scanner-service.ts
  extensions/ql-vscode/src/log-insights/log-scanner.ts
  extensions/ql-vscode/src/log-insights/log-summary.ts
  extensions/ql-vscode/src/log-insights/summary-language-support.ts
  extensions/ql-vscode/src/log-insights/summary-parser.ts
  extensions/ql-vscode/src/pure/log-summary-parser.ts
  extensions/ql-vscode/src/pure/messages.ts
  extensions/ql-vscode/src/query-history.ts
  extensions/ql-vscode/src/query-results.ts
  extensions/ql-vscode/src/queryserver-client.ts
  extensions/ql-vscode/src/run-queries.ts
  extensions/ql-vscode/src/vscode-tests/no-workspace/eval-log-tree-builder.test.ts
  extensions/ql-vscode/test/pure-tests/evaluator-log-summaries/bad-join-order.jsonl
  extensions/ql-vscode/test/pure-tests/log-scanner.test.ts
  extensions/ql-vscode/test/pure-tests/log-summary-parser.test.ts
Labels: Complexity: Medium

#1468 Add `implements` and `signature` to syntax highlighting
  extensions/ql-vscode/syntaxes/ql.tmLanguage.yml
  syntaxes/ql.tmLanguage.json
Labels: bug, Complexity: Low

#1487 Restart CLI server too when restarting query server
  extensions/ql-vscode/src/cli.ts
  extensions/ql-vscode/src/extension.ts
Labels: bug, Complexity: Low
