Repository github/vscode-codeql, pull requests merged in 2023-03, with the labels that each got.

#2120 Add controller repo 'learn more' link
  extensions/ql-vscode/package.json
Labels: secexp

#2124 Move variant analysis tests out from the CLI integration test suite
  extensions/ql-vscode/test/vscode-tests/activated-extension/jest.setup.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/data/variant-analysis-results.zip
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-results-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/jest.setup.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/jest.activated-extension.setup.ts
Labels: secexp

#2123 Remove additional `as unknown as` for database items
  extensions/ql-vscode/test/vscode-tests/no-workspace/astViewer.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/astBuilder.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/fileRangeFromURI.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/queryResolver.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/interface-utils.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/test-adapter.test.ts
  extensions/ql-vscode/test/vscode-tests/utils/mocking.helpers.ts
Labels: secexp

#2115 Cleanup config to enabling new telemetry
  extensions/ql-vscode/src/config.ts
  extensions/ql-vscode/src/telemetry.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts
Labels: secexp

#2122 Remove `as unknown as QuickPickItem`
  extensions/ql-vscode/test/vscode-tests/cli-integration/packaging.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/databaseFetcher.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/utils/mocking.helpers.ts
Labels: secexp

#2138 Fix VS Marketplace badge
  README.md
Labels: secexp

#2136 Upgrade to Husky 8
  .husky/pre-commit
  .husky/pre-push
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
Labels: secexp

#2141 Tidy up docs
  CONTRIBUTING.md
  docs/images/highlighted-code-snippet.png
  docs/images/results-table.png
  docs/releasing.md
  docs/test-plan.md
  docs/testing.md
Labels: secexp

#2143 Update release process to lock/unlock the main branch
  docs/releasing.md
Labels: secexp

#2144 Prepare for MRVA public beta
  README.md
  docs/test-plan.md
  extensions/ql-vscode/CHANGELOG.md
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/databases/db-module.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/variant-analysis/repository-selection.ts
  extensions/ql-vscode/src/variant-analysis/run-remote-query.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
Labels: secexp

#2142 Extension Telemetry: Split `runVariantAnalysis` and `viewAst` command
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2154 Extension Telemetry: Split `viewCfg`,`quickEval`, `openReferencedFile` command
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2148 Add commands package inside src directory
  extensions/ql-vscode/src/packages/commands/CommandManager.ts
  extensions/ql-vscode/src/packages/commands/index.ts
  extensions/ql-vscode/test/unit-tests/packages/commands/CommandManager.test.ts
Labels: secexp

#2151 Add check for error message for packaging.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/packaging.test.ts
Labels: secexp

#2150 Do not copy `node_modules` when packaging
  extensions/ql-vscode/gulpfile.ts/deploy.ts
  extensions/ql-vscode/gulpfile.ts/package.ts
Labels: secexp

#2169 Use `TeeLogger` instead of `additionalLogLocation:` option
  extensions/ql-vscode/src/common/logging/index.ts
  extensions/ql-vscode/src/common/logging/logger.ts
  extensions/ql-vscode/src/common/logging/tee-logger.ts
  extensions/ql-vscode/src/common/logging/vscode/output-channel-logger.ts
  extensions/ql-vscode/src/legacy-query-server/queryserver-client.ts
  extensions/ql-vscode/src/legacy-query-server/run-queries.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/src/query-results.ts
  extensions/ql-vscode/src/query-serialization.ts
  extensions/ql-vscode/src/query-server/queryserver-client.ts
  extensions/ql-vscode/src/query-server/run-queries.ts
  extensions/ql-vscode/src/run-queries-shared.ts
  extensions/ql-vscode/test/__mocks__/loggerMock.ts
  extensions/ql-vscode/test/common/logging/output-channel-logger.test.ts
  extensions/ql-vscode/test/factories/query-history/local-query-history-item.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-serialization.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/run-queries.test.ts
Labels: code cleanup, Complexity: Medium

#2164 Unify `commandRunner` implementations
  extensions/ql-vscode/src/commandRunner.ts
Labels: secexp

#2165 Simpler `withProgress` calls
  extensions/ql-vscode/src/commandRunner.ts
  extensions/ql-vscode/src/contextual/templateProvider.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/local-databases.ts
Labels: secexp

#2157 Commands registration
  extensions/ql-vscode/src/common/app.ts
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/common/vscode/commands.ts
  extensions/ql-vscode/src/common/vscode/vscode-app.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/packages/commands/CommandManager.ts
  extensions/ql-vscode/src/packages/commands/Disposable.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-view-manager.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts
  extensions/ql-vscode/test/__mocks__/appMock.ts
  extensions/ql-vscode/test/__mocks__/commandsMock.ts
  extensions/ql-vscode/test/factories/extension-context.ts
  extensions/ql-vscode/test/unit-tests/packages/commands/CommandManager.test.ts
Labels: secexp

#2171 Convert run variant analysis command to new commands package
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
Labels: secexp

#2172 Add new data flow paths view (empty)
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/interface-utils.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/variant-analysis/data-flow-paths-view.ts
  extensions/ql-vscode/src/variant-analysis/shared/data-flow-paths.ts
  extensions/ql-vscode/src/view/data-flow-paths/DataFlowPathsView.tsx
  extensions/ql-vscode/src/view/data-flow-paths/__tests__/DataFlowPathsView.spec.tsx
  extensions/ql-vscode/src/view/data-flow-paths/index.tsx
  extensions/ql-vscode/test/factories/variant-analysis/shared/data-flow-paths.ts
Labels: secexp

#2182 Wire up data flow paths view
  extensions/ql-vscode/CHANGELOG.md
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/stories/common/CodePaths.stories.tsx
  extensions/ql-vscode/src/stories/data-flow-paths/DataFlowPaths.stories.tsx
  extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts
  extensions/ql-vscode/src/view/common/CodePaths/CodePaths.tsx
  extensions/ql-vscode/src/view/common/CodePaths/CodePathsOverlay.tsx
  extensions/ql-vscode/src/view/common/CodePaths/__tests__/CodePaths.spec.tsx
  extensions/ql-vscode/src/view/data-flow-paths/DataFlowPaths.tsx
  extensions/ql-vscode/src/view/data-flow-paths/DataFlowPathsView.tsx
  extensions/ql-vscode/src/view/data-flow-paths/__tests__/DataFlowPaths.spec.tsx
  extensions/ql-vscode/src/view/data-flow-paths/__tests__/DataFlowPathsView.spec.tsx
  extensions/ql-vscode/test/factories/variant-analysis/shared/data-flow-paths.ts
Labels: secexp

#2176 Convert query history commands to typed commands
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
Labels: secexp

#2183 Remove primer packages and make styled-components a top-level dependency
  CONTRIBUTING.md
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
Labels: secexp

#2190 Convert new database panel to typed commands
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/databases/db-module.ts
  extensions/ql-vscode/src/databases/ui/db-panel.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2189 Convert local database commands to typed commands
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/local-databases-ui.ts
Labels: secexp

#2193 Move query-serialization
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/src/query-history/store/query-history-store.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/store/query-history-store.test.ts
Labels: secexp

#2195 Move remaining local database commands to databases UI
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/local-databases-ui.ts
Labels: secexp

#2201 Convert codeQLEvalLogViewer.clear to a typed command
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/eval-log-viewer.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2200 Convert codeQL.restartQueryServer to a typed command
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2198 Convert packaging to typed commands
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/packaging.ts
Labels: secexp

#2196 Convert AST and CFG commands to typed commands
  extensions/ql-vscode/src/ast-cfg-commands.ts
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2203 Convert AST viewer commands to typed commands
  extensions/ql-vscode/src/astViewer.ts
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2204 Convert summary language commands to typed commands
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/log-insights/summary-language-support.ts
Labels: secexp

#2208 Convert mock API server commands to typed commands
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/mocks/vscode-mock-gh-api-server.ts
Labels: secexp

#2209 Convert query editing commands to typed commands
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/query-editor.ts
Labels: secexp

#2207 Start using app.commands.execute for all commands called from extension.ts
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2210 Convert some base commands to typed commands
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2213 Add `codeQL.checkForUpdatesToCLI` type for command
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2214 Remove `commandRunnerWithProgress`
  extensions/ql-vscode/src/commandRunner.ts
Labels: secexp

#2215 Rename and move `commandRunner`
  extensions/ql-vscode/src/commandRunner.ts
  extensions/ql-vscode/src/common/vscode/commands.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2219 Remove remaining references to `commandRunner`
  extensions/ql-vscode/src/common/vscode/commands.ts
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2217 Convert call sites to use typed commands (part 1)
  extensions/ql-vscode/src/cli.ts
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/databaseFetcher.ts
  extensions/ql-vscode/src/databases/db-module.ts
  extensions/ql-vscode/src/databases/ui/db-panel.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/helpers.ts
  extensions/ql-vscode/src/legacy-query-server/queryserver-client.ts
  extensions/ql-vscode/src/local-databases-ui.ts
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/query-editor.ts
  extensions/ql-vscode/src/test-ui.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/databaseFetcher.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/legacy-query.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
Labels: secexp

#2222 Convert call sites to use typed commands (part 2): QueryHistoryManager
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/src/vscode-utils/external-files.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-tree-data-provider.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/vscode-utils/external-files.test.ts
Labels: secexp

#2227 Only retry tests in CI
  .github/workflows/main.yml
  extensions/ql-vscode/test/vscode-tests/jest.activated-extension.setup.ts
  extensions/ql-vscode/test/vscode-tests/jest.setup.ts
Labels: secexp

#2230 Use undefined instead of Record<string, never> type when unable to activate extension
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/databases/db-panel.test.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/databaseFetcher.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/helpers.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/legacy-query.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/packaging.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/run-cli.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
  extensions/ql-vscode/test/vscode-tests/global.helper.ts
  extensions/ql-vscode/test/vscode-tests/jest.activated-extension.setup.ts
Labels: secexp

#2231 Rename query history read and write methods
  extensions/ql-vscode/src/legacy-query-server/run-queries.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/src/query-history/store/query-history-store.ts
  extensions/ql-vscode/src/query-results.ts
  extensions/ql-vscode/src/run-queries-shared.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/store/query-history-store.test.ts
Labels: secexp

#2229 Convert call sites to use typed commands (part 3)
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/log-insights/summary-language-support.ts
  extensions/ql-vscode/src/mocks/vscode-mock-gh-api-server.ts
  extensions/ql-vscode/src/query-server/queryserver-client.ts
  extensions/ql-vscode/src/variant-analysis/export-results.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-monitor.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts
Labels: secexp

#2235 Convert call sites to use typed commands (part 5): VariantAnalysisView
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-view-serializer.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts
Labels: secexp

#2236 Commit autogenerated changes to codeql-pack.lock.yml
  extensions/ql-vscode/test/vscode-tests/cli-integration/data/codeql-pack.lock.yml
Labels: secexp

#2247 Use gh release create instead of deprecated actions
  .github/workflows/release.yml
Labels: secexp

#2237 Convert call sites to use typed commands (part 6): createVSCodeCommandManager in tests
  extensions/ql-vscode/test/vscode-tests/activated-extension/databases/db-panel.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/sourcemap.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-submission-integration.test.ts
Labels: secexp

#2249 Improve monitor error message
  extensions/ql-vscode/src/variant-analysis/variant-analysis-monitor.ts
Labels: secexp

#2244 Refactor local query evaluation to prepare for debug adapter
  extensions/ql-vscode/src/ast-cfg-commands.ts
  extensions/ql-vscode/src/common/logging/logger.ts
  extensions/ql-vscode/src/contextual/astBuilder.ts
  extensions/ql-vscode/src/contextual/locationFinder.ts
  extensions/ql-vscode/src/contextual/queryResolver.ts
  extensions/ql-vscode/src/contextual/templateProvider.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/helpers.ts
  extensions/ql-vscode/src/legacy-query-server/legacyRunner.ts
  extensions/ql-vscode/src/legacy-query-server/run-queries.ts
  extensions/ql-vscode/src/legacy-query-server/upgrades.ts
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/local-queries.ts
  extensions/ql-vscode/src/query-results.ts
  extensions/ql-vscode/src/query-server/query-runner.ts
  extensions/ql-vscode/src/query-server/run-queries.ts
  extensions/ql-vscode/src/queryRunner.ts
  extensions/ql-vscode/src/run-queries-shared.ts
  extensions/ql-vscode/test/common/logging/output-channel-logger.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/contextual/astBuilder.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/run-queries.test.ts
Labels: code cleanup, Complexity: High, tech-debt

#2245 Move `LocalQueries` commands to be member functions
  extensions/ql-vscode/src/local-queries.ts
Labels: code cleanup, Complexity: Low

#2246 Move extension pack resolution into `LocalQueries`
  extensions/ql-vscode/src/contextual/queryResolver.ts
  extensions/ql-vscode/src/legacy-query-server/legacyRunner.ts
  extensions/ql-vscode/src/legacy-query-server/run-queries.ts
  extensions/ql-vscode/src/local-queries.ts
  extensions/ql-vscode/src/query-server/query-runner.ts
  extensions/ql-vscode/src/query-server/run-queries.ts
  extensions/ql-vscode/src/queryRunner.ts
Labels: code cleanup, Complexity: Low
