Repository github/vscode-codeql, pull requests merged in 2023-04, with the labels that each got.

#2255 Add simple regression unit test for the results view
  extensions/ql-vscode/src/view/jest.config.ts
  extensions/ql-vscode/src/view/results/__tests__/results.spec.tsx
Labels: secexp

#2168 Enable React strict mode
  extensions/ql-vscode/src/view/webview.tsx
Labels: secexp

#2262 Add empty data extension editor view
  CODEOWNERS
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/interface-utils.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
  extensions/ql-vscode/src/view/data-extensions-editor/index.tsx
  extensions/ql-vscode/src/view/vscode-api.ts
Labels: secexp

#2261 Repo States: Extract read/write methods to repo states store
  extensions/ql-vscode/src/variant-analysis/store/repo-states-store.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
Labels: secexp

#2272 Split up codeQL.monitorVariantAnalysis command
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
Labels: secexp

#2263 Show external API calls in data extensions editor
  extensions/ql-vscode/src/data-extensions-editor/bqrs.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/external-api-usage.ts
  extensions/ql-vscode/src/data-extensions-editor/modeled-method.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
  extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx
  extensions/ql-vscode/src/view/data-extensions-editor/__tests__/supported.spec.ts
  extensions/ql-vscode/src/view/data-extensions-editor/supported.ts
  extensions/ql-vscode/test/unit-tests/data-extensions-editor/bqrs.test.ts
Labels: secexp

#2275 Fix markdownlint errors for generated files
  extensions/ql-vscode/src/variant-analysis/markdown-generation.ts
  extensions/ql-vscode/test/unit-tests/data/markdown-generation/.markdownlint.jsonc
  extensions/ql-vscode/test/unit-tests/data/markdown-generation/interpreted-results/path-problem/expected/result-1-github-codeql.md
  extensions/ql-vscode/test/unit-tests/data/markdown-generation/interpreted-results/path-problem/expected/result-2-meteor-meteor.md
  extensions/ql-vscode/test/unit-tests/data/markdown-generation/interpreted-results/problem/expected/_summary.md
  extensions/ql-vscode/test/unit-tests/data/markdown-generation/raw-results/expected/_summary.md
  extensions/ql-vscode/test/unit-tests/data/markdown-generation/raw-results/expected/result-1-github-codeql.md
  extensions/ql-vscode/test/unit-tests/data/markdown-generation/raw-results/expected/result-2-meteor-meteor.md
Labels: secexp

#2269 Upgrade ts-jest
  extensions/ql-vscode/package-lock.json
Labels: dependencies, secexp

#2276 Add markdownlint to CI
  .github/workflows/main.yml
Labels: secexp

#2264 Add saving of data extension editor table to YAML
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/yaml.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
  extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts
Labels: secexp

#2265 Load existing data extension YAML in editor
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/yaml.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
  extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts
Labels: secexp

#2242 Query History: create and map data model to domain model
  extensions/ql-vscode/src/legacy-query-server/run-queries.ts
  extensions/ql-vscode/src/query-history/store/data-mapper.ts
  extensions/ql-vscode/src/query-history/store/domain-mapper.ts
  extensions/ql-vscode/src/query-history/store/local-query-data-item.ts
  extensions/ql-vscode/src/query-history/store/query-history-data.ts
  extensions/ql-vscode/src/query-history/store/query-history-store.ts
  extensions/ql-vscode/src/query-history/store/variant-analysis-data-item.ts
  extensions/ql-vscode/src/query-results.ts
  extensions/ql-vscode/src/run-queries-shared.ts
Labels: secexp

#2266 Add link to example usage in data extensions editor
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx
Labels: secexp

#2270 Repo States: new data model and mapping
  extensions/ql-vscode/src/variant-analysis/store/repo-states-data-types.ts
  extensions/ql-vscode/src/variant-analysis/store/repo-states-store.ts
  extensions/ql-vscode/src/variant-analysis/store/repo-states-to-data-mapper.ts
  extensions/ql-vscode/src/variant-analysis/store/repo-states-to-domain-mapper.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/variant-analysis/variant-analysis-manager.test.ts
Labels: secexp

#2280 Fix error when closing MRVA webview during extension activation
  extensions/ql-vscode/src/variant-analysis/variant-analysis-view-serializer.ts
Labels: secexp

#2281 Repo task: new data model and mapping
  extensions/ql-vscode/src/variant-analysis/store/repo-states-store.ts
  extensions/ql-vscode/src/variant-analysis/store/repo-task-data-types.ts
  extensions/ql-vscode/src/variant-analysis/store/repo-task-store.ts
  extensions/ql-vscode/src/variant-analysis/store/repo-task-to-data-mapper.ts
  extensions/ql-vscode/src/variant-analysis/store/repo-task-to-domain-mapper.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-results-manager.ts
Labels: secexp

#2267 Add generating of flow model to data extension editor
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts
  extensions/ql-vscode/src/data-extensions-editor/modeled-method.ts
  extensions/ql-vscode/src/data-extensions-editor/yaml.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
Labels: secexp

#2260 Add stories for data extension editor
  extensions/ql-vscode/.babelrc.json
  extensions/ql-vscode/.storybook/main.ts
  extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx
  extensions/ql-vscode/src/stories/data-extensions-editor/MethodRow.stories.tsx
  extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
Labels: secexp

#2288 Update selected code flow when data flow paths change
  extensions/ql-vscode/CHANGELOG.md
  extensions/ql-vscode/src/view/data-flow-paths/DataFlowPaths.tsx
Labels: secexp

#2293 Use data extensions for finding external API calls
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
Labels: secexp

#2294 Don't rate limit if no CLI is installed
  extensions/ql-vscode/src/distribution.ts
Labels: secexp

#2279 Fix empty result view when switching between queries
  extensions/ql-vscode/src/view/results/__tests__/results.spec.tsx
  extensions/ql-vscode/src/view/results/result-tables.tsx
Labels: secexp

#2250 Adapt skeleton pack generation to work with new queries panel
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/databaseFetcher.ts
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/local-queries.ts
  extensions/ql-vscode/src/qlpack-generator.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/databaseFetcher.test.ts
Labels: secexp

#2256 Improvements to skeleton query flow
  extensions/ql-vscode/src/databaseFetcher.ts
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Labels: secexp

#2297 Refactor `digForDatabaseItem` and `digForDatabaseWithSameLanguage` methods for skeleton wizard
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/factories/databases/databases.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
Labels: secexp

#2295 Add configurable model filename to data extension editor
  extensions/ql-vscode/src/cli.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
Labels: secexp

#2298 Fix problem with detecting storage folder on windows
  extensions/ql-vscode/src/local-queries.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Labels: secexp

#2305 Small fixes to skeleton query wizard
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/local-queries.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
Labels: secexp

#2304 Make types for selection commands more precise
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/local-queries.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
Labels: secexp

#2308 Query history store renaming
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/src/query-history/store/data-mapper.ts
  extensions/ql-vscode/src/query-history/store/domain-mapper.ts
  extensions/ql-vscode/src/query-history/store/index.ts
  extensions/ql-vscode/src/query-history/store/local-query-data-item.ts
  extensions/ql-vscode/src/query-history/store/query-history-data.ts
  extensions/ql-vscode/src/query-history/store/query-history-domain-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-dto-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-dto.ts
  extensions/ql-vscode/src/query-history/store/query-history-local-query-dto.ts
  extensions/ql-vscode/src/query-history/store/query-history-store.ts
  extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-dto.ts
Labels: secexp

#2313 Repo tasks store renaming
  extensions/ql-vscode/src/variant-analysis/repo-tasks-store/index.ts
  extensions/ql-vscode/src/variant-analysis/repo-tasks-store/repo-tasks-domain-mapper.ts
  extensions/ql-vscode/src/variant-analysis/repo-tasks-store/repo-tasks-dto-mapper.ts
  extensions/ql-vscode/src/variant-analysis/repo-tasks-store/repo-tasks-dto.ts
  extensions/ql-vscode/src/variant-analysis/repo-tasks-store/repo-tasks-store.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-results-manager.ts
Labels: secexp

#2312 Filter out databases with errors
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Labels: secexp

#2316 Improve error handling in data extension editor
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/data-schema.json
  extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts
  extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts
  extensions/ql-vscode/src/data-extensions-editor/yaml.ts
  extensions/ql-vscode/test/unit-tests/data-extensions-editor/yaml.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
Labels: secexp

#2323 Update `@types/vscode` and fix naming conflicts
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/databases/ui/db-panel.ts
  extensions/ql-vscode/test/vscode-tests/activated-extension/databases/db-panel.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
Labels: Complexity: Low, Update dependencies

#2315 Introduce mapping layer for variant analysis history items
  extensions/ql-vscode/src/query-history/store/query-history-domain-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-dto-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-domain-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-dto-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-variant-analysis-dto.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data/variant-analysis/workspace-query-history.json
Labels: secexp

#2314 Add external APIs query in extension
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts
  extensions/ql-vscode/src/data-extensions-editor/queries/index.ts
  extensions/ql-vscode/src/data-extensions-editor/queries/java.ts
  extensions/ql-vscode/src/data-extensions-editor/queries/query.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
Labels: secexp

#2322 Move local query mappers to separate files
  extensions/ql-vscode/src/query-history/store/query-history-domain-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-dto-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-local-query-domain-mapper.ts
  extensions/ql-vscode/src/query-history/store/query-history-local-query-dto-mapper.ts
Labels: secexp

#2296 Allow creating new model file in existing data extension
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
Labels: secexp

#2300 Add creating extension packs when opening the editor
  extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts
  extensions/ql-vscode/src/helpers.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
Labels: secexp

#2302 Change kind input to a dropdown
  extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts
  extensions/ql-vscode/src/data-extensions-editor/predicates.ts
  extensions/ql-vscode/src/data-extensions-editor/yaml.ts
  extensions/ql-vscode/src/view/data-extensions-editor/KindInput.tsx
  extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx
Labels: secexp

#2310 Stop pushing QL pack as top level folder to avoid confusing the user
  extensions/ql-vscode/src/helpers.ts
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/qlpack-generator.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
Labels: secexp

#2334 Add database language check to data extensions editor
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
Labels: secexp

#2306 Use native VS Code test UI on canary
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/cli.ts
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/test-adapter.ts
  extensions/ql-vscode/src/test-manager-base.ts
  extensions/ql-vscode/src/test-manager.ts
  extensions/ql-vscode/src/test-runner.ts
  extensions/ql-vscode/src/test-ui.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/test-adapter.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/test-runner-helpers.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/test-runner.test.ts
Labels: Complexity: Medium, Update dependencies, tech-debt

#2291 Implement basic CodeQL debug adapter
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/debugger/debug-configuration.ts
  extensions/ql-vscode/src/debugger/debug-protocol.ts
  extensions/ql-vscode/src/debugger/debug-session.ts
  extensions/ql-vscode/src/debugger/debugger-factory.ts
  extensions/ql-vscode/src/debugger/debugger-ui.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/legacy-query-server/run-queries.ts
  extensions/ql-vscode/src/local-databases-ui.ts
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/local-queries.ts
  extensions/ql-vscode/src/progress.ts
  extensions/ql-vscode/src/run-queries-shared.ts
  extensions/ql-vscode/test/data/.gitignore
  extensions/ql-vscode/test/data/.vscode/launch.json
  extensions/ql-vscode/test/data/textfile.txt
  extensions/ql-vscode/test/unit-tests/command-lint.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/data/QuickEvalLib.qll
  extensions/ql-vscode/test/vscode-tests/cli-integration/data/QuickEvalQuery.ql
  extensions/ql-vscode/test/vscode-tests/cli-integration/debugger/debug-controller.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/debugger/debugger.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
  extensions/ql-vscode/test/vscode-tests/global.helper.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/determining-selected-query-test.ts
Labels: enhancement, Complexity: High

#2342 Revert "Bump @storybook/builder-webpack5 (#2320)"
  extensions/ql-vscode/package-lock.json
  extensions/ql-vscode/package.json
Labels: secexp

#2337 Fix error when model file does not exist
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
Labels: secexp

#2339 Show model filename in data extensions editor
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx
  extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
Labels: secexp

#2345 Filter extension packs by database item language
  extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
Labels: secexp

#2328 Ensure we're selecting database in single rooted workspace
  extensions/ql-vscode/src/databaseFetcher.ts
  extensions/ql-vscode/src/local-databases-ui.ts
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
Labels: secexp

#2348 Hide link when model file does not exist
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts
  extensions/ql-vscode/src/data-extensions-editor/shared/extension-pack.ts
  extensions/ql-vscode/src/data-extensions-editor/shared/view-state.ts
  extensions/ql-vscode/src/pure/interface-types.ts
  extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx
  extensions/ql-vscode/src/view/data-extensions-editor/DataExtensionsEditor.tsx
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/extension-pack-picker.test.ts
Labels: secexp

#2341 Prompt non-codespace users for storage path
  extensions/ql-vscode/package.json
  extensions/ql-vscode/src/config.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Labels: secexp

#2343 Add a component for filtering repositories based on their results
  extensions/ql-vscode/CHANGELOG.md
  extensions/ql-vscode/src/pure/variant-analysis-filter-sort.ts
  extensions/ql-vscode/src/stories/variant-analysis/RepositoriesFilter.stories.tsx
  extensions/ql-vscode/src/view/variant-analysis/RepositoriesFilter.tsx
  extensions/ql-vscode/src/view/variant-analysis/RepositoriesSearchSortRow.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisSkippedRepositoriesTab.tsx
  extensions/ql-vscode/test/unit-tests/variant-analysis-filter-sort.test.ts
Labels: secexp

#2330 Select latest database when creating skeleton query
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
Labels: secexp

#2347 Break down local-queries.ts
  extensions/ql-vscode/src/ast-cfg-commands.ts
  extensions/ql-vscode/src/debugger/debug-configuration.ts
  extensions/ql-vscode/src/debugger/debugger-factory.ts
  extensions/ql-vscode/src/debugger/debugger-ui.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/local-queries/local-queries.ts
  extensions/ql-vscode/src/local-queries/local-query-run.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
Labels: secexp

#2321 Enable skeleton wizard in codespaces-codeql template
  extensions/ql-vscode/package.json
  extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
Labels: secexp

#2355 Introduce index.ts for local-queries module
  extensions/ql-vscode/src/ast-cfg-commands.ts
  extensions/ql-vscode/src/debugger/debug-configuration.ts
  extensions/ql-vscode/src/debugger/debugger-factory.ts
  extensions/ql-vscode/src/debugger/debugger-ui.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/local-queries/index.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
Labels: secexp

#2354 Clear pack cache on create and delete
  extensions/ql-vscode/src/extension.ts
Labels: secexp

#2357 Move Query Server files
  extensions/ql-vscode/src/contextual/locationFinder.ts
  extensions/ql-vscode/src/contextual/queryResolver.ts
  extensions/ql-vscode/src/contextual/templateProvider.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts
  extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts
  extensions/ql-vscode/src/debugger/debug-session.ts
  extensions/ql-vscode/src/debugger/debugger-factory.ts
  extensions/ql-vscode/src/debugger/debugger-ui.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/local-databases-ui.ts
  extensions/ql-vscode/src/local-databases.ts
  extensions/ql-vscode/src/local-queries/local-queries.ts
  extensions/ql-vscode/src/local-queries/local-query-run.ts
  extensions/ql-vscode/src/query-editor.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/src/query-results.ts
  extensions/ql-vscode/src/query-server/index.ts
  extensions/ql-vscode/src/query-server/legacy/index.ts
  extensions/ql-vscode/src/query-server/legacy/legacy-query-runner.ts
  extensions/ql-vscode/src/query-server/legacy/query-server-client.ts
  extensions/ql-vscode/src/query-server/legacy/run-queries.ts
  extensions/ql-vscode/src/query-server/legacy/upgrades.ts
  extensions/ql-vscode/src/query-server/new-query-runner.ts
  extensions/ql-vscode/src/query-server/query-runner.ts
  extensions/ql-vscode/src/query-server/query-server-client.ts
  extensions/ql-vscode/src/query-server/run-queries.ts
  extensions/ql-vscode/src/query-server/server-process.ts
  extensions/ql-vscode/src/queryRunner.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/debugger/debug-controller.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/legacy-query.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/new-query.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-tree-data-provider.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/store/query-history-store.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-results.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/run-queries.test.ts
Labels: secexp

#2360 Move language support files
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/language-support/ide-server.ts
  extensions/ql-vscode/src/language-support/index.ts
  extensions/ql-vscode/src/language-support/language-support.ts
  extensions/ql-vscode/src/language-support/query-editor.ts
Labels: secexp

#2367 Move local query files
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/local-queries/index.ts
  extensions/ql-vscode/src/local-queries/local-queries.ts
  extensions/ql-vscode/src/local-queries/quick-eval-code-lens-provider.ts
  extensions/ql-vscode/src/local-queries/quick-query.ts
  extensions/ql-vscode/src/run-queries-shared.ts
Labels: secexp

#2369 Only attempt to discover QL tests in on-disk workspace folders
  extensions/ql-vscode/src/helpers.ts
  extensions/ql-vscode/src/test-manager.ts
Labels: bug, Complexity: Low

#2371 Rename `Argument[-1]` to `Argument[this]`
  extensions/ql-vscode/src/stories/data-extensions-editor/DataExtensionsEditor.stories.tsx
  extensions/ql-vscode/src/stories/data-extensions-editor/MethodRow.stories.tsx
  extensions/ql-vscode/src/view/data-extensions-editor/MethodRow.tsx
Labels: secexp

#2377 Move database files
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/compare/compare-view.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts
  extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts
  extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts
  extensions/ql-vscode/src/databases/database-fetcher.ts
  extensions/ql-vscode/src/databases/local-databases-ui.ts
  extensions/ql-vscode/src/databases/local-databases.ts
  extensions/ql-vscode/src/debugger/debugger-ui.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/interface-utils.ts
  extensions/ql-vscode/src/interface.ts
  extensions/ql-vscode/src/language-support/ast-viewer/ast-builder.ts
  extensions/ql-vscode/src/language-support/ast-viewer/ast-viewer.ts
  extensions/ql-vscode/src/language-support/contextual/file-range-from-uri.ts
  extensions/ql-vscode/src/language-support/contextual/location-finder.ts
  extensions/ql-vscode/src/language-support/contextual/query-resolver.ts
  extensions/ql-vscode/src/language-support/contextual/template-provider.ts
  extensions/ql-vscode/src/local-queries/local-queries.ts
  extensions/ql-vscode/src/local-queries/local-query-run.ts
  extensions/ql-vscode/src/local-queries/quick-query.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/src/query-server/legacy/legacy-query-runner.ts
  extensions/ql-vscode/src/query-server/legacy/run-queries.ts
  extensions/ql-vscode/src/query-server/legacy/upgrades.ts
  extensions/ql-vscode/src/query-server/new-query-runner.ts
  extensions/ql-vscode/src/query-server/query-runner.ts
  extensions/ql-vscode/src/run-queries-shared.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/src/test-runner.ts
  extensions/ql-vscode/test/factories/databases/databases.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/databases/database-fetcher.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/debugger/debugger.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/skeleton-query-wizard.test.ts
  extensions/ql-vscode/test/vscode-tests/global.helper.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/data-extensions-editor/external-api-usage-query.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/databases/database-fetcher.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/databases/local-databases-ui.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/language-support/contextual/file-range-from-uri.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/history-tree-data-provider.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/run-queries.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/test-adapter.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/test-runner-helpers.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/test-runner.test.ts
  extensions/ql-vscode/test/vscode-tests/utils/mocking.helpers.ts
Labels: secexp

#2287 Introduce helpers for commands that operate on selections
  extensions/ql-vscode/src/common/selection-commands.ts
  extensions/ql-vscode/src/databases/local-databases-ui.ts
  extensions/ql-vscode/src/local-queries/local-queries.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/query-history-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-history/variant-analysis-history.test.ts
Labels: secexp

#2349 Show number of successful repos instead of completed repos in variant analysis results view header
  extensions/ql-vscode/src/stories/variant-analysis/VariantAnalysisStats.stories.tsx
  extensions/ql-vscode/src/variant-analysis/shared/variant-analysis.ts
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisHeader.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisRepositoriesStats.tsx
  extensions/ql-vscode/src/view/variant-analysis/VariantAnalysisStats.tsx
  extensions/ql-vscode/src/view/variant-analysis/__tests__/VariantAnalysisStats.spec.tsx
Labels: secexp

#2384 Fix not setting database as selected if it already exists
  extensions/ql-vscode/CHANGELOG.md
  extensions/ql-vscode/src/databases/local-databases.ts
  extensions/ql-vscode/src/test-runner.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/test-runner.test.ts
Labels: secexp

#2389 Add missing changelog entry for #2349
  extensions/ql-vscode/CHANGELOG.md
Labels: secexp

#2388 Move vscode utils to /common/vscode
  extensions/ql-vscode/src/codeql-cli/distribution.ts
  extensions/ql-vscode/src/common/vscode/abstract-webview.ts
  extensions/ql-vscode/src/common/vscode/archive-filesystem-provider.ts
  extensions/ql-vscode/src/common/vscode/authentication.ts
  extensions/ql-vscode/src/common/vscode/commands.ts
  extensions/ql-vscode/src/common/vscode/external-files.ts
  extensions/ql-vscode/src/common/vscode/multi-file-system-watcher.ts
  extensions/ql-vscode/src/common/vscode/progress.ts
  extensions/ql-vscode/src/common/vscode/vscode-app.ts
  extensions/ql-vscode/src/compare/compare-view.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-module.ts
  extensions/ql-vscode/src/data-extensions-editor/data-extensions-editor-view.ts
  extensions/ql-vscode/src/data-extensions-editor/extension-pack-picker.ts
  extensions/ql-vscode/src/data-extensions-editor/external-api-usage-query.ts
  extensions/ql-vscode/src/data-extensions-editor/generate-flow-model.ts
  extensions/ql-vscode/src/databases/database-fetcher.ts
  extensions/ql-vscode/src/databases/local-databases-ui.ts
  extensions/ql-vscode/src/databases/local-databases.ts
  extensions/ql-vscode/src/databases/ui/db-panel.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/helpers.ts
  extensions/ql-vscode/src/interface.ts
  extensions/ql-vscode/src/language-support/ast-viewer/ast-cfg-commands.ts
  extensions/ql-vscode/src/language-support/contextual/location-finder.ts
  extensions/ql-vscode/src/language-support/contextual/query-resolver.ts
  extensions/ql-vscode/src/language-support/contextual/template-provider.ts
  extensions/ql-vscode/src/local-queries/local-queries.ts
  extensions/ql-vscode/src/local-queries/quick-query.ts
  extensions/ql-vscode/src/packaging/packaging.ts
  extensions/ql-vscode/src/qltest-discovery.ts
  extensions/ql-vscode/src/query-history/query-history-manager.ts
  extensions/ql-vscode/src/query-server/legacy/legacy-query-runner.ts
  extensions/ql-vscode/src/query-server/legacy/query-server-client.ts
  extensions/ql-vscode/src/query-server/legacy/run-queries.ts
  extensions/ql-vscode/src/query-server/legacy/upgrades.ts
  extensions/ql-vscode/src/query-server/new-query-runner.ts
  extensions/ql-vscode/src/query-server/query-runner.ts
  extensions/ql-vscode/src/query-server/query-server-client.ts
  extensions/ql-vscode/src/query-server/run-queries.ts
  extensions/ql-vscode/src/run-queries-shared.ts
  extensions/ql-vscode/src/skeleton-query-wizard.ts
  extensions/ql-vscode/src/telemetry.ts
  extensions/ql-vscode/src/variant-analysis/data-flow-paths-view.ts
  extensions/ql-vscode/src/variant-analysis/export-results.ts
  extensions/ql-vscode/src/variant-analysis/repository-selection.ts
  extensions/ql-vscode/src/variant-analysis/run-remote-query.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-manager.ts
  extensions/ql-vscode/src/variant-analysis/variant-analysis-view.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/queries.test.ts
  extensions/ql-vscode/test/vscode-tests/cli-integration/variant-analysis/variant-analysis-manager.test.ts
  extensions/ql-vscode/test/vscode-tests/global.helper.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/local-databases.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/common/vscode/archive-filesystem-provider.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/common/vscode/external-files.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/helpers.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/telemetry.test.ts
Labels: secexp

#2391 Move query testing related files to /query-testing
  extensions/ql-vscode/src/common/commands.ts
  extensions/ql-vscode/src/extension.ts
  extensions/ql-vscode/src/query-testing/discovery.ts
  extensions/ql-vscode/src/query-testing/qltest-discovery.ts
  extensions/ql-vscode/src/query-testing/test-adapter.ts
  extensions/ql-vscode/src/query-testing/test-manager-base.ts
  extensions/ql-vscode/src/query-testing/test-manager.ts
  extensions/ql-vscode/src/query-testing/test-runner.ts
  extensions/ql-vscode/src/query-testing/test-tree-node.ts
  extensions/ql-vscode/src/query-testing/test-ui.ts
  extensions/ql-vscode/test/vscode-tests/minimal-workspace/query-testing/qltest-discovery.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-adapter.test.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-runner-helpers.ts
  extensions/ql-vscode/test/vscode-tests/no-workspace/query-testing/test-runner.test.ts
Labels: secexp
